/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get product by id
         * @description Cross-tenant access returns 404.
         */
        get: operations["get"];
        /** Update product (partial) */
        put: operations["update"];
        post?: never;
        /** Delete product (hard delete) */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products (tenant-scoped) */
        get: operations["list"];
        put?: never;
        /** Create product (stock starts at 0) */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/stock-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 出库（库存 -）
         * @description 库存不足 → 400 INSUFFICIENT_STOCK
         */
        post: operations["stockOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/stock-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 入库（库存 +） */
        post: operations["stockIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * CSV 批量导入商品
         * @description 表头：name,code,unit,price,stockQuantity,remark；逐行校验，部分成功。
         */
        post: operations["importCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stock movements (tenant-scoped) */
        get: operations["listMovements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count products (tenant-scoped) */
        get: operations["count"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/_health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateProductRequest: {
            name?: string;
            code?: string;
            unit?: string;
            price?: number;
            remark?: string;
        };
        CreateProductRequest: {
            name: string;
            code?: string;
            unit?: string;
            price?: number;
            remark?: string;
        };
        /** @description 商品（进销存 · inventory-service 独占） */
        Product: {
            /**
             * Format: int64
             * @description Auto-assigned primary key
             */
            readonly id?: number;
            /**
             * Format: int64
             * @description Owning tenant (logical ref -> user-service tenants.id; no DB FK per ADR-0025)
             */
            tenantId: number;
            /**
             * @description 商品名称
             * @example 联想 ThinkPad X1 Carbon
             */
            name: string;
            /**
             * @description 商品编码（SKU，租户内可唯一）
             * @example SKU-001
             */
            code?: string;
            /**
             * @description 计量单位
             * @example 台 / 件 / kg
             */
            unit?: string;
            /**
             * @description 单价（元）
             * @example 8999
             */
            price?: number;
            /**
             * Format: int32
             * @description 当前库存量（出入库自动增减）
             * @example 42
             */
            readonly stockQuantity?: number;
            /** @description 备注 */
            remark?: string;
            /**
             * Format: int64
             * @description 创建人（逻辑 ref -> users.id）
             */
            readonly createdBy?: number;
            /**
             * Format: int64
             * @description 最后更新人
             */
            readonly updatedBy?: number;
            /**
             * Format: date-time
             * @description Create timestamp
             */
            readonly createdAt?: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            readonly updatedAt?: string;
        };
        StockChangeRequest: {
            /** Format: int32 */
            quantity?: number;
            remark?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                /**
                 * @description Product id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Product"];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Product"];
                };
            };
            /** @description Product not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Product"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                /**
                 * @description Product id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductRequest"];
            };
        };
        responses: {
            /** @description Updated product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description Product not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                /**
                 * @description Product id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Product not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description 关键字（名称/编码模糊） */
                keyword?: string;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of products (may be empty) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description Created product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Product"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Product"];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Product"];
                };
            };
        };
    };
    stockOut: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                /**
                 * @description Product id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockChangeRequest"];
            };
        };
        responses: {
            /** @description Updated product with new stock */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description INSUFFICIENT_STOCK */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description Product not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    stockIn: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                /**
                 * @description Product id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockChangeRequest"];
            };
        };
        responses: {
            /** @description Updated product with new stock */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description Product not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    importCsv: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 导入结果 {total, success, failed, errors} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    listMovements: {
        parameters: {
            query?: {
                /** @description IN / OUT 过滤 */
                type?: string;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                /**
                 * @description Product id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of movements (may be empty) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    count: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
