/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ledger/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ledger entry by id */
        get: operations["get"];
        /** Update ledger entry (partial) */
        put: operations["update"];
        post?: never;
        /** Delete ledger entry */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ledger entries (tenant-scoped) */
        get: operations["list"];
        put?: never;
        /** Create ledger entry */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 收支汇总（income / expense / balance） */
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/summary/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 月度收支（按 YYYY-MM 分组，默认最近 6 个月） */
        get: operations["monthlySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/_health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateEntryRequest: {
            type?: string;
            amount?: number;
            category?: string;
            /** Format: date */
            occurredAt?: string;
            remark?: string;
        };
        CreateEntryRequest: {
            type: string;
            amount: number;
            category?: string;
            /** Format: date */
            occurredAt: string;
            remark?: string;
        };
        /** @description 记账流水（财务 · finance-service 独占） */
        LedgerEntry: {
            /**
             * Format: int64
             * @description Auto-assigned primary key
             */
            readonly id?: number;
            /**
             * Format: int64
             * @description Owning tenant
             */
            tenantId: number;
            /**
             * @description INCOME 收入 / EXPENSE 支出
             * @example INCOME
             * @enum {string}
             */
            type: "INCOME" | "EXPENSE";
            /**
             * @description 金额（元，>0）
             * @example 12800
             */
            amount: number;
            /**
             * @description 分类（如 销售收入 / 房租 / 工资 / 采购）
             * @example 销售收入
             */
            category?: string;
            /**
             * Format: date
             * @description 业务发生日期
             * @example 2026-08-23
             */
            occurredAt: string;
            /** @description 备注 */
            remark?: string;
            /**
             * Format: int64
             * @description 记帐人（逻辑 ref -> users.id）
             */
            readonly createdBy?: number;
            /**
             * Format: date-time
             * @description Create timestamp
             */
            readonly createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                /**
                 * @description Entry id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LedgerEntry"];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LedgerEntry"];
                };
            };
            /** @description Not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LedgerEntry"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                /**
                 * @description Entry id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEntryRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description Not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                /**
                 * @description Entry id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description INCOME / EXPENSE 过滤 */
                type?: string;
                /** @description 分类模糊 */
                category?: string;
                /** @description 开始日期 yyyy-MM-dd */
                from?: string;
                /** @description 结束日期 yyyy-MM-dd */
                to?: string;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List (may be empty) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntryRequest"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LedgerEntry"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LedgerEntry"];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LedgerEntry"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: {
                /** @description 开始日期 yyyy-MM-dd */
                from?: string;
                /** @description 结束日期 yyyy-MM-dd */
                to?: string;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    monthlySummary: {
        parameters: {
            query?: {
                /** @description 月数（1-24，默认 6） */
                months?: number;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monthly list (newest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
