/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List approval requests (tenant-scoped) */
        get: operations["list"];
        put?: never;
        /** 发起审批（PENDING） */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 驳回（PENDING → REJECTED · 仅审批人 · comment 必填） */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销（PENDING → CANCELLED · 仅发起人） */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 通过（PENDING → APPROVED · 仅审批人） */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get approval request by id */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 待办计数（工作台角标） */
        get: operations["counts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审批操作审计（租户内 · append-only · 阶段 2） */
        get: operations["auditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/_health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateApprovalRequest: {
            type: string;
            title: string;
            amount?: number;
            detail?: string;
            /** Format: int64 */
            approverId?: number;
        };
        /** @description 通用审批请求（approval-service 独占） */
        ApprovalRequest: {
            /**
             * Format: int64
             * @description Auto-assigned primary key
             */
            readonly id?: number;
            /**
             * Format: int64
             * @description Owning tenant
             */
            tenantId: number;
            /**
             * @description EXPENSE 支出/报销 / PURCHASE 采购 / SALE 销售出库 / OTHER 其他
             * @example EXPENSE
             * @enum {string}
             */
            type: "EXPENSE" | "PURCHASE" | "SALE" | "OTHER";
            /**
             * @description 审批标题
             * @example 报销 8 月差旅费
             */
            title: string;
            /**
             * @description 金额（元，金额类单据填）
             * @example 1280
             */
            amount?: number;
            /** @description 详情（JSON 文本或自由描述） */
            detail?: string;
            /**
             * Format: int64
             * @description 发起人（逻辑 ref -> users.id，来自 X-User-Id）
             */
            requesterId: number;
            /**
             * Format: int64
             * @description 指定审批人（逻辑 ref -> users.id）
             */
            approverId: number;
            /**
             * @description 审批状态
             * @example PENDING
             * @enum {string}
             */
            status: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED";
            /** @description 审批意见（驳回必填）/ 撤销原因 */
            comment?: string;
            /**
             * Format: int64
             * @description 决策人（审批人 或 撤销的发起人）
             */
            readonly decidedBy?: number;
            /**
             * Format: date-time
             * @description 决策时间
             */
            readonly decidedAt?: string;
            /**
             * Format: date-time
             * @description Create timestamp
             */
            readonly createdAt?: string;
            /**
             * Format: date-time
             * @description Update timestamp
             */
            readonly updatedAt?: string;
        };
        RejectRequest: {
            comment: string;
        };
        DecideRequest: {
            comment?: string;
        };
        ApprovalAuditLog: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            tenantId?: number;
            /** @enum {string} */
            action?: "CREATE" | "APPROVE" | "REJECT" | "CANCEL";
            /** Format: int64 */
            resourceId?: number;
            /** Format: int64 */
            actorId?: number;
            /** @enum {string} */
            outcome?: "SUCCESS" | "FAILURE";
            detail?: string;
            sourceIp?: string;
            userAgent?: string;
            requestId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: {
                /** @description mine=我发起的 / inbox=待我审批 / all=全部（默认） */
                role?: string;
                /** @description EXPENSE / PURCHASE / SALE / OTHER 过滤 */
                type?: string;
                /** @description PENDING / APPROVED / REJECTED / CANCELLED 过滤 */
                status?: string;
            };
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List (may be empty) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"][];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApprovalRequest"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                /**
                 * @description Approval id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description FORBIDDEN（非审批人） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description Not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description ALREADY_DECIDED（非待审批） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                /**
                 * @description Approval id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecideRequest"];
            };
        };
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description FORBIDDEN（非发起人） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description Not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description ALREADY_DECIDED（非待审批） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                /**
                 * @description Approval id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecideRequest"];
            };
        };
        responses: {
            /** @description Approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description FORBIDDEN（非审批人） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description Not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description ALREADY_DECIDED（非待审批） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                /**
                 * @description Approval id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description Not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalRequest"];
                };
            };
        };
    };
    counts: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: number;
                    };
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    auditLogs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit logs (newest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalAuditLog"][];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApprovalAuditLog"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
