/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get lead detail */
        get: operations["get"];
        /** Update lead (not allowed after CONVERTED) */
        put: operations["update"];
        post?: never;
        /** Soft-delete lead */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get customer by id
         * @description Tenant-scoped: cross-tenant access returns 404 (no existence leak).
         */
        get: operations["get_1"];
        /**
         * Update customer (partial)
         * @description 传入字段才更新；跨租户访问返回 404。updated_by 取 X-User-Id。
         */
        put: operations["update_1"];
        post?: never;
        /**
         * Delete customer (soft delete)
         * @description 置 is_deleted = true；列表/详情立即不可见。跨租户访问返回 404。
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List leads (tenant-scoped)
         * @description 必须带 X-Tenant-Id；可选 status / owner / keyword 过滤。owner=-1 只看线索池（未认领），0 全部，>0 指定认领人。
         */
        get: operations["list"];
        put?: never;
        /**
         * Create lead (into pool)
         * @description 新建线索进池，ownerId 为空。
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release lead back to pool */
        post: operations["release"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}/follow-ups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List follow-up timeline */
        get: operations["listFollowUps"];
        put?: never;
        /** Add follow-up (timeline) */
        post: operations["addFollowUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convert lead to customer
         * @description 复制线索信息创建客户并关联，线索置 CONVERTED。
         */
        post: operations["convert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign lead to current user (claim from pool) */
        post: operations["assign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk import leads (CSV)
         * @description 表头：name,contactName,contactPhone,email,source,remark；逐行校验，部分成功；导入进线索池（来源默认 IMPORT）。
         */
        post: operations["importCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List customers (tenant-scoped)
         * @description 必须带 X-Tenant-Id；可选 keyword（名称/联系人/电话模糊）与 status（NEW/FOLLOWING/CONVERTED/LOST）过滤。
         */
        get: operations["list_1"];
        put?: never;
        /**
         * Create customer
         * @description tenant_id 强制取请求租户（X-Tenant-Id），请求体不允许指定租户；created_by 取 X-User-Id。
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * CSV 批量导入客户
         * @description 表头：name,contactName,contactPhone,email,address,status,ownerId,remark；逐行校验，部分成功。
         */
        post: operations["importCsv_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count customers (tenant-scoped, non-deleted) */
        get: operations["count"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/_health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenant audit logs
         * @description Requires X-Tenant-Id (ADR-0025).
         */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit-logs/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count tenant audit logs */
        get: operations["count_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 线索创建 / 更新请求 */
        LeadRequest: {
            /**
             * @description 线索名称（公司 / 个人）
             * @example 南昌星火贸易有限公司
             */
            name: string;
            /**
             * @description 联系人
             * @example 李经理
             */
            contactName?: string;
            /**
             * @description 联系电话
             * @example 13900000000
             */
            contactPhone?: string;
            /**
             * Format: email
             * @description 邮箱
             * @example lead@xinghuo.cn
             */
            email?: string;
            /**
             * @description 来源：MANUAL / IMPORT / CHANNEL / OTHER（缺省 MANUAL）
             * @example CHANNEL
             */
            source?: string;
            /**
             * @description 备注
             * @example 官网留资，意向较强
             */
            remark?: string;
        };
        UpdateCustomerRequest: {
            name?: string;
            contactName?: string;
            contactPhone?: string;
            /** Format: email */
            email?: string;
            address?: string;
            status?: string;
            /** Format: int64 */
            ownerId?: number;
            remark?: string;
        };
        /** @description 线索跟进记录请求 */
        FollowUpRequest: {
            /**
             * @description 跟进方式：PHONE / VISIT / WECHAT / NOTE（缺省 NOTE）
             * @example PHONE
             */
            type?: string;
            /**
             * @description 跟进内容
             * @example 电话沟通，客户对报价感兴趣，约下周面谈
             */
            content: string;
            /**
             * Format: date-time
             * @description 下次跟进时间（ISO-8601）
             * @example 2026-09-01T10:00:00Z
             */
            nextFollowUpAt?: string;
        };
        CreateCustomerRequest: {
            name: string;
            contactName?: string;
            contactPhone?: string;
            /** Format: email */
            email?: string;
            address?: string;
            status?: string;
            /** Format: int64 */
            ownerId?: number;
            remark?: string;
        };
        /** @description 客户实体（CRM · crm-service 独占） */
        Customer: {
            /**
             * Format: int64
             * @description Auto-assigned primary key
             * @example 1
             */
            readonly id?: number;
            /**
             * Format: int64
             * @description Owning tenant (logical ref -> user-service tenants.id; no DB FK per ADR-0025)
             * @example 1
             */
            tenantId: number;
            /**
             * @description 客户名称（公司 / 个人）
             * @example 南昌伍盟企业服务有限公司
             */
            name: string;
            /**
             * @description 联系人
             * @example 王经理
             */
            contactName?: string;
            /**
             * @description 联系电话
             * @example 13800000000
             */
            contactPhone?: string;
            /**
             * @description 邮箱
             * @example contact@wumeng.cn
             */
            email?: string;
            /**
             * @description 地址
             * @example 江西省南昌市红谷滩区
             */
            address?: string;
            /**
             * @description 跟进状态：NEW / FOLLOWING / CONVERTED / LOST
             * @example FOLLOWING
             * @enum {string}
             */
            status: "NEW" | "FOLLOWING" | "CONVERTED" | "LOST";
            /**
             * Format: int64
             * @description 负责人（逻辑 ref -> user-service users.id）
             * @example 1
             */
            readonly ownerId?: number;
            /**
             * @description 备注
             * @example 重点客户，季度续费
             */
            remark?: string;
            /**
             * Format: int64
             * @description 创建人（逻辑 ref -> users.id，gateway X-User-Id 注入）
             */
            readonly createdBy?: number;
            /**
             * Format: int64
             * @description 最后更新人（逻辑 ref -> users.id）
             */
            readonly updatedBy?: number;
            /**
             * Format: date-time
             * @description Create timestamp (server-assigned)
             */
            readonly createdAt?: string;
            /**
             * Format: date-time
             * @description Last update timestamp (server-assigned)
             */
            readonly updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                /**
                 * @description Customer id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Customer"];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Customer"];
                };
            };
            /** @description Customer not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Customer"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                /**
                 * @description Customer id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerRequest"];
            };
        };
        responses: {
            /** @description Updated customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description Validation error / invalid status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description Customer not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                /**
                 * @description Customer id
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Customer not found (or cross-tenant) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description 状态过滤 NEW/FOLLOWING/CONVERTED/LOST */
                status?: string;
                /** @description 认领人过滤：-1=线索池 0=全部 >0=指定人 */
                owner?: number;
                /** @description 关键字（名称/联系人/电话模糊） */
                keyword?: string;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    release: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    listFollowUps: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    addFollowUp: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowUpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    convert: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    assign: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    importCsv: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                /** @description 关键字（名称/联系人/电话模糊匹配） */
                keyword?: string;
                /** @description 跟进状态过滤 */
                status?: string;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of customers (may be empty) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerRequest"];
            };
        };
        responses: {
            /** @description Created customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Customer"];
                };
            };
            /** @description Validation error / invalid status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Customer"];
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Customer"];
                };
            };
        };
    };
    importCsv_1: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 导入结果 {total, success, failed, errors} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    count: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description TENANT_CONTEXT_REQUIRED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                action?: string;
                resourceType?: string;
                limit?: number;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    count_1: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
}
