/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user by id
     * @description Tenant-scoped: cross-tenant access returns 404.
     */
    get: operations["get"];
    /**
     * Update user (partial)
     * @description Update displayName/email/phone/status/roles; password only when provided. username immutable.
     */
    put: operations["update"];
    post?: never;
    /** Delete user by id */
    delete: operations["delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tenants/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get tenant by id */
    get: operations["get_1"];
    /**
     * Update tenant (name / status)
     * @description Rename or enable/disable a tenant. DISABLED blocks login for its users.
     */
    put: operations["update_1"];
    post?: never;
    /**
     * Delete tenant (only when it has no users)
     * @description Hard delete is only allowed for empty tenants. Use DISABLED status to decommission tenants with users.
     */
    delete: operations["delete_1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/roles/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update role (name/description/scope)
     * @description PLATFORM_ADMIN only; code immutable; system roles read-only.
     */
    put: operations["update_2"];
    post?: never;
    /**
     * Delete custom role
     * @description PLATFORM_ADMIN only; system roles cannot be deleted.
     */
    delete: operations["delete_2"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List users
     * @description Tenant-scoped: if X-Tenant-Id header present, only that tenant's users.
     */
    get: operations["list"];
    put?: never;
    /**
     * Create user
     * @description Body must include username + displayName + plaintext password (will be hashed). email/phone optional.
     */
    post: operations["create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/{id}/login-marker": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark last login (service-to-service, called by auth-service on successful login) */
    post: operations["markLastLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/verification/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify one-time code (marks used) */
    post: operations["verify"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/verification/send": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send one-time code (SMS/EMAIL) */
    post: operations["send"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tenants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all tenants
     * @description Return every tenant (no pagination yet).
     */
    get: operations["list_1"];
    put?: never;
    /**
     * Provision tenant (开租户)
     * @description Create a tenant with unique code. This is the core 'offline sale -> provision' step.
     */
    post: operations["create_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tenants/{tenantId}/invites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List invites of tenant */
    get: operations["list_2"];
    put?: never;
    /** Generate invite code for tenant */
    post: operations["create_2"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tenants/{tenantId}/invites/{id}/revoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke invite code */
    post: operations["revoke"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tenants/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Self-service tenant registration (public)
     * @description 创建租户 + 管理员（TENANT_ADMIN），注册即开通（ACTIVE 可直接登录）。公开端点，无鉴权。
     */
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List roles
     * @description PLATFORM_ADMIN or TENANT_ADMIN can read.
     */
    get: operations["list_3"];
    put?: never;
    /**
     * Create custom role
     * @description PLATFORM_ADMIN only.
     */
    post: operations["create_3"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/count": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Count users */
    get: operations["count"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/by-username/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user by username (admin Feign internal) */
    get: operations["byUsername"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/auth/by-tenant/{tenantCode}/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user auth view by tenant (service-to-service, contains passwordHash)
     * @description INTERNAL endpoint for auth-service only. Resolve tenant by code then user by (tenant_id, username).
     */
    get: operations["authByTenantAndUsername"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/auth/by-phone/{phone}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user auth view by phone (service-to-service) */
    get: operations["authByPhone"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/auth/by-email/{email}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user auth view by email (service-to-service) */
    get: operations["authByEmail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/_health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health probe */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/audit-logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List audit logs
     * @description Tenant-scoped; platform admin without tenant sees all.
     */
    get: operations["list_4"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/audit-logs/count": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Count audit logs */
    get: operations["count_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UpdateUserRequest: {
      displayName?: string;
      email?: string;
      phone?: string;
      status?: string;
      roles?: string[];
      password?: string;
    };
    UpdateTenantRequest: {
      name?: string;
      status?: string;
      edition?: string;
    };
    UpdateRoleRequest: {
      name?: string;
      scope?: string;
      description?: string;
    };
    CreateUserRequest: {
      username: string;
      displayName: string;
      password: string;
      email?: string;
      phone?: string;
      tenantCode?: string;
      inviteCode?: string;
    };
    VerifyCodeRequest: {
      channel: string;
      target: string;
      purpose: string;
      code: string;
    };
    SendCodeRequest: {
      channel: string;
      target: string;
      purpose: string;
    };
    CreateTenantRequest: {
      name: string;
      code: string;
      edition?: string;
    };
    CreateInviteRequest: {
      role?: string;
      /** Format: int32 */
      expiresInDays?: number;
      /** Format: int32 */
      maxUses?: number;
    };
    RegisterTenantRequest: {
      tenantName: string;
      tenantCode: string;
      username: string;
      displayName: string;
      password: string;
      email?: string;
    };
    CreateRoleRequest: {
      code: string;
      name: string;
      scope?: string;
      description?: string;
    };
    /** @description User entity owned by user-service */
    User: {
      /**
       * Format: int64
       * @description Auto-assigned primary key
       * @example 1
       */
      readonly id?: number;
      /**
       * Format: int64
       * @description Owning tenant (FK -> tenants.id); mandatory since ADR-0022 multitenancy
       * @example 1
       */
      tenantId: number;
      /**
       * @description Login username (unique within tenant)
       * @example futurewl
       */
      username: string;
      /**
       * @description Human display name
       * @example Future Wang
       */
      displayName: string;
      /**
       * @description Email (optional, unique; NULL excluded from unique constraint)
       * @example future@huntercat.cn
       */
      email?: string;
      /**
       * @description Phone (optional)
       * @example 13800000000
       */
      phone?: string;
      /** @description BCrypt hash; NEVER exposed via public endpoints. Use /api/users/auth/by-username for service-to-service. */
      passwordHash?: string;
      /**
       * @description Account status
       * @example ACTIVE
       * @enum {string}
       */
      status: "ACTIVE" | "DISABLED" | "LOCKED";
      /**
       * Format: date-time
       * @description Create timestamp (server-assigned)
       */
      readonly createdAt?: string;
      /**
       * Format: date-time
       * @description Last update timestamp (server-assigned)
       */
      readonly updatedAt?: string;
      /**
       * Format: date-time
       * @description Last successful login timestamp (auth-service writes back)
       */
      readonly lastLoginAt?: string;
      roles?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get: {
    parameters: {
      query?: never;
      header?: {
        "X-Tenant-Id"?: string;
      };
      path: {
        /**
         * @description User id
         * @example 1
         */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
      /** @description User not found (or cross-tenant) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
    };
  };
  update: {
    parameters: {
      query?: never;
      header?: {
        "X-Tenant-Id"?: string;
        "X-User-Id"?: string;
      };
      path: {
        /**
         * @description User id
         * @example 1
         */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRequest"];
      };
    };
    responses: {
      /** @description Updated user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Invalid status value */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  delete: {
    parameters: {
      query?: never;
      header?: {
        "X-Tenant-Id"?: string;
        "X-User-Id"?: string;
      };
      path: {
        /** @description User id */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_1: {
    parameters: {
      query?: never;
      header?: {
        "X-User-Roles"?: string;
      };
      path: {
        /**
         * @description Tenant id
         * @example 1
         */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tenant found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Requires PLATFORM_ADMIN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Tenant not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  update_1: {
    parameters: {
      query?: never;
      header?: {
        "X-User-Roles"?: string;
        "X-User-Id"?: string;
        "X-Tenant-Id"?: string;
      };
      path: {
        /**
         * @description Tenant id
         * @example 1
         */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTenantRequest"];
      };
    };
    responses: {
      /** @description Updated tenant */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Invalid status value */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Requires PLATFORM_ADMIN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Tenant not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  delete_1: {
    parameters: {
      query?: never;
      header?: {
        "X-User-Roles"?: string;
        "X-User-Id"?: string;
        "X-Tenant-Id"?: string;
      };
      path: {
        /**
         * @description Tenant id
         * @example 1
         */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires PLATFORM_ADMIN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tenant not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tenant still has users; decommission with DISABLED instead */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_2: {
    parameters: {
      query?: never;
      header?: {
        "X-User-Roles"?: string;
        "X-User-Id"?: string;
        "X-Tenant-Id"?: string;
      };
      path: {
        /**
         * @description Role id
         * @example 1
         */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateRoleRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description System role is read-only */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Role not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  delete_2: {
    parameters: {
      query?: never;
      header?: {
        "X-User-Roles"?: string;
        "X-User-Id"?: string;
        "X-Tenant-Id"?: string;
      };
      path: {
        /**
         * @description Role id
         * @example 1
         */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description System role cannot be deleted */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Role not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  list: {
    parameters: {
      query?: never;
      header?: {
        "X-Tenant-Id"?: string;
        "X-User-Roles"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of users (may be empty) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: {
        "X-Tenant-Id"?: string;
        "X-User-Id"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"];
      };
    };
    responses: {
      /** @description Created user with assigned id + passwordHash */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  markLastLogin: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description User id
         * @example 1
         */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Marked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  verify: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyCodeRequest"];
      };
    };
    responses: {
      /** @description Valid, consumed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description CODE_NOT_FOUND / CODE_EXPIRED / CODE_MISMATCH */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  send: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendCodeRequest"];
      };
    };
    responses: {
      /** @description Sent */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description SEND_TOO_FREQUENT / invalid channel */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  list_1: {
    parameters: {
      query?: never;
      header?: {
        "X-User-Roles"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of tenants (may be empty) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Requires PLATFORM_ADMIN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  create_1: {
    parameters: {
      query?: never;
      header?: {
        "X-User-Roles"?: string;
        "X-User-Id"?: string;
        "X-Tenant-Id"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTenantRequest"];
      };
    };
    responses: {
      /** @description Provisioned tenant */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Invalid input / code already taken */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Requires PLATFORM_ADMIN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  list_2: {
    parameters: {
      query?: never;
      header?: {
        "X-User-Roles"?: string;
        "X-Tenant-Id"?: string;
      };
      path: {
        /**
         * @description Tenant id
         * @example 1
         */
        tenantId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of invites (newest first) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  create_2: {
    parameters: {
      query?: never;
      header?: {
        "X-User-Roles"?: string;
        "X-Tenant-Id"?: string;
      };
      path: {
        /**
         * @description Tenant id
         * @example 1
         */
        tenantId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateInviteRequest"];
      };
    };
    responses: {
      /** @description Invite created with code */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Tenant not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  revoke: {
    parameters: {
      query?: never;
      header?: {
        "X-User-Roles"?: string;
        "X-Tenant-Id"?: string;
      };
      path: {
        /**
         * @description Tenant id
         * @example 1
         */
        tenantId: number;
        /**
         * @description Invite id
         * @example 1
         */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Invite not found / belongs to other tenant */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterTenantRequest"];
      };
    };
    responses: {
      /** @description Registered tenant + admin */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Invalid input / code taken / weak password */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  list_3: {
    parameters: {
      query?: never;
      header?: {
        "X-User-Roles"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of roles */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  create_3: {
    parameters: {
      query?: never;
      header?: {
        "X-User-Roles"?: string;
        "X-User-Id"?: string;
        "X-Tenant-Id"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRoleRequest"];
      };
    };
    responses: {
      /** @description Created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Code taken */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  count: {
    parameters: {
      query?: never;
      header?: {
        "X-Tenant-Id"?: string;
        "X-User-Roles"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  byUsername: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Username
         * @example futurewl
         */
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
    };
  };
  authByTenantAndUsername: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Tenant code
         * @example huntercat
         */
        tenantCode: string;
        /** @description Username */
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description UserAuthView returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description Tenant or user not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  authByPhone: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Phone
         * @example 13800000000
         */
        phone: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description UserAuthView returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  authByEmail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Email
         * @example user@huntercat.cn
         */
        email: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description UserAuthView returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_4: {
    parameters: {
      query?: {
        action?: string;
        resourceType?: string;
        outcome?: string;
        limit?: number;
      };
      header?: {
        "X-Tenant-Id"?: string;
        "X-User-Roles"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Audit logs (newest first) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  count_1: {
    parameters: {
      query?: never;
      header?: {
        "X-Tenant-Id"?: string;
        "X-User-Roles"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
}
