/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/iot/topo/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 批量保存节点位置（upsert；不在请求内的旧节点清理） */
        put: operations["saveNodes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新规则 */
        put: operations["update"];
        post?: never;
        /** 删除规则 */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 产品详情（含属性定义 + 命令定义） */
        get: operations["detail"];
        /** 更新产品 */
        put: operations["update_1"];
        post?: never;
        /** 删除产品（同时删除其属性/命令定义；有设备的产品禁止删除） */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 设备详情（含影子快照） */
        get: operations["detail_1"];
        /** 更新设备（名称/分组/标签/备注） */
        put: operations["update_2"];
        post?: never;
        /** 删除设备（连带清理拓扑节点/连线） */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/devices/{deviceKey}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 属性上报（网关转发设备报文 → 影子 + 时序 + 规则评估） */
        post: operations["telemetry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/devices/{deviceKey}/online": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 设备上线（网关会话建立） */
        post: operations["online"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/devices/{deviceKey}/offline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 设备离线（网关会话断开/心跳超时） */
        post: operations["offline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/devices/{deviceKey}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 设备登录上报（MAC/CCID → 登录事件 + 影子快照） */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/devices/{deviceKey}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 事件上报（网关转发设备事件 → 事件表 + 规则评估） */
        post: operations["event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/devices/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 设备认证（网关握手时校验 deviceKey/deviceSecret） */
        post: operations["auth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/topo/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加连线（源 → 目标；重复 409 / 自环 400） */
        post: operations["addLink"];
        /** 删除连线（source + target） */
        delete: operations["removeLink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 规则列表（租户内） */
        get: operations["list"];
        put?: never;
        /** 创建规则 */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 产品列表（租户内，可选关键字） */
        get: operations["list_1"];
        put?: never;
        /** 创建产品 */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/products/{productId}/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加属性定义 */
        post: operations["addProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/products/{productId}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加命令定义 */
        post: operations["addCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 设备列表（租户内 · 产品/状态/关键字过滤，附影子摘要：最高节点温度/信号/未确认告警） */
        get: operations["list_2"];
        put?: never;
        /** 创建设备（自动生成 deviceKey/deviceSecret；私有协议设备可自定义） */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/devices/{id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传设备照片（multipart file，≤10MB，image/*）→ 返回可访问 photoUrl */
        post: operations["upload"];
        /** 删除设备照片（清 photoUrl + 删文件） */
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/devices/{id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动下发命令（经 device-gateway 写入设备会话） */
        post: operations["sendCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/rules/{id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 启用/停用规则 */
        patch: operations["setEnabled"];
        trace?: never;
    };
    "/api/iot/alerts/{id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 确认告警（PENDING → ACKNOWLEDGED · 幂等） */
        patch: operations["acknowledge"];
        trace?: never;
    };
    "/api/iot/topo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 拓扑快照（节点坐标 + 连线，设备信息由 /api/iot/devices 提供） */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/photos/{tenantId}/{deviceId}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取照片（公开静态 · UUID 不可枚举 · 7 天缓存） */
        get: operations["read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/devices/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 属性时序（时间范围查询，最近 1000 条） */
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/devices/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 设备事件（时间范围查询，最近 500 条） */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/devices/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 监控总览（统计卡 + 全站最高温度 + 离线/告警设备列表） */
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/devices/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 设备健康聚合（驾驶舱：局放/电池/信号/最热节点，一次拉全量影子摘要） */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/devices/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 设备数量统计（总 + 在线） */
        get: operations["count"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 告警列表（租户内 · 状态/级别/设备/关键字过滤 + 时间窗口） */
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/products/{productId}/properties/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除属性定义 */
        delete: operations["removeProperty"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/iot/products/{productId}/commands/{commandId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除命令定义 */
        delete: operations["removeCommand"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NodePosition: {
            /** Format: int64 */
            deviceId?: number;
            /** Format: float */
            x?: number;
            /** Format: float */
            y?: number;
        };
        RuleRequest: {
            name: string;
            enabled?: boolean;
            severity?: string;
            triggerType: string;
            /** Format: int64 */
            productId: number;
            propertyKey?: string;
            operator?: string;
            threshold?: string;
            /** Format: int32 */
            windowSec?: number;
            eventKey?: string;
            actionsJson: string;
            description?: string;
        };
        CreateProductRequest: {
            name: string;
            code?: string;
            protocolType: string;
            description?: string;
            enabled?: boolean;
        };
        CreateDeviceRequest: {
            name: string;
            /** Format: int64 */
            productId: number;
            deviceKey?: string;
            deviceSecret?: string;
            groupName?: string;
            installAddress?: string;
            photoUrl?: string;
            tagsJson?: string;
            remark?: string;
        };
        LinkBody: {
            /** Format: int64 */
            source?: number;
            /** Format: int64 */
            target?: number;
        };
        /** @description 产品属性定义（物模型） */
        ProductProperty: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            productId?: number;
            /**
             * @description 属性 key（设备报文中的字段名）
             * @example temperature
             */
            name?: string;
            /**
             * @description 显示名
             * @example 温度
             */
            label?: string;
            /**
             * @description 数据类型
             * @example NUMBER
             * @enum {string}
             */
            dataType?: "NUMBER" | "STRING" | "BOOL" | "ENUM";
            /**
             * @description 单位
             * @example °C
             */
            unit?: string;
            /**
             * @description 读写权限
             * @example R
             * @enum {string}
             */
            rw?: "R" | "RW";
            /** Format: int32 */
            sortOrder?: number;
            description?: string;
        };
        /** @description 产品命令定义（物模型） */
        ProductCommand: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            productId?: number;
            /**
             * @description 命令 key（下发给设备的命令名）
             * @example setThreshold
             */
            name?: string;
            /**
             * @description 显示名
             * @example 设置阈值
             */
            label?: string;
            /**
             * @description 参数定义（JSON 数组）
             * @example [
             *       {
             *         "name": "threshold",
             *         "label": "阈值",
             *         "dataType": "NUMBER"
             *       }
             *     ]
             */
            paramsJson?: string;
            description?: string;
        };
        SendCommandRequest: {
            command: string;
            params?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    saveNodes: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodePosition"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    detail_1: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeviceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    telemetry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    online: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    offline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    auth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    addLink: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    removeLink: {
        parameters: {
            query: {
                source: number;
                target: number;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                keyword?: string;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    addProperty: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductProperty"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    addCommand: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                productId?: number;
                status?: string;
                keyword?: string;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeviceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    sendCommand: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendCommandRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    setEnabled: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    acknowledge: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-User-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                deviceId: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    history: {
        parameters: {
            query?: {
                propertyKey?: string;
                days?: number;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    events: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    count: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                status?: string;
                severity?: string;
                deviceId?: number;
                keyword?: string;
                days?: number;
            };
            header?: {
                "X-Tenant-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    removeProperty: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                productId: number;
                propertyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    removeCommand: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
            };
            path: {
                productId: number;
                commandId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
}
